config: &config
  package-ecosystem: npm
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - davemcorwin
  - amirbey
  assignees:
  - davemcorwin

version: 2
updates:
- directory: "/"
  <<: *config
- directory: "/admin-client"
  <<: *config
