version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    # Disable version updates for npm dependencies
    # This still allows for security updates but is pretty sloppy configuration from Github
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    open-pull-requests-limit: 0
    commit-message:
      prefix: '[ci skip] '
  - package-ecosystem: npm
    directory: /admin-client # admin client
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: '[ci skip] '
  - package-ecosystem: npm
    directory: /apps/metrics # metrics app
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: '[ci skip] '
