config: &config
  package-ecosystem: npm
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - davemcorwin
  - amirbey
  assignees:
  - davemcorwin

version: 2
updates:
- directory: "/"
  <<: *config
  ignore:
    # Permanent
    - dependency-name: "uswds"
    # Temporary
    - dependency-name: "autoprefixer"
    - dependency-name: "js-yaml"
    - dependency-name: "postcss-loader"
    - dependency-name: "react"
    - dependency-name: "react-dom"
    - dependency-name: "sass-loader"
    - dependency-name: "socker.io"
    - dependency-name: "socket.io-client"
    - dependency-name: "webpack"
- directory: "/admin-client"
  <<: *config
