version: '3'

volumes:
  db-data:
  yarn:
  nm-app:
  nm-admin:

services:
  app:
    build:
      dockerfile: Dockerfile-app
      context: .
    command: ["scripts/wait-for-it.sh", "db:5432", "--", "yarn", "watch"]
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
      - /app/admin-client/
      - nm-app:/app/node_modules
    ports:
      - "1337:1337" # for the app itself
      - "8888:8888" # for viewing analyze-webpack
      - "8080:8080" # for serving test coverage html
    depends_on:
      - db
      - redis
      - uaa
    environment:
      JWT_SECRET: 'shhHhh...'
      USER_AUDITOR: federalist
      FEATURE_PROXY_EDGE_LINKS: 'false'
      FEATURE_PROXY_EDGE_DYNAMO: 'false'
      APP_HOSTNAME: http://localhost:1337
      AUTH_IDP: uaa
      UAA_HOST: http://localhost:9000
      UAA_HOST_DOCKER_URL: http://uaa:8080
  admin-client:
    build:
      dockerfile: ./admin-client/Dockerfile-admin
      context: .
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - ./admin-client:/app
      - nm-admin:/app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - app
    command: ["yarn", "dev"]
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # expose db on host at port 5433
    environment:
      POSTGRES_DB: federalist
      POSTGRES_TEST_DB: federalist-test
      POSTGRES_PASSWORD: password
  redis:
    image: redis
    ports:
      - 6379:6379
  uaa:
    build:
      dockerfile: ./Dockerfile-uaa
      context: .
    ports:
      - 9000:8080
    environment:
      POSTGRES_DB: federalist
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db
    command: ["/tomcat/bin/catalina.sh", "run"]
