version: '3'

services:
  app:
    image: node:14
    volumes:
      - ../..:/app
    depends_on:
      - db
      - redis
    environment:
      FEATURE_ADMIN_AUTH: 'true'
      AUTH_IDP: uaa
      YARN_VERSION: 0.24.6-1
      CC_TEST_REPORTER_ID: 101a439651b6abd27e5440028a53b5b8f08fe0889f3948d5f58f6cf9f7c786a0
      CONCOURSE: 'true'
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:5-alpine