############################
#  SHARED

node-image: &node-image
  type: docker-image
  source:
    repository: node
    tag: 14


############################
#  JOBS

jobs:

  - name: build
    plan:
      - do:
        - in_parallel:
          - get: staging
            trigger: true
            params: {depth: 1}
          - get: redis
            params: {save: true}
          - get: postgres
            params: {save: true}
          - get: node
            params: {save: true}        
        - in_parallel:
          - do:
            - task: api-install-deps
              config:
                platform: linux
                image_resource:
                  <<: *node-image
                inputs: [name: staging]
                outputs: [name: staging]
                run:
                  dir: staging
                  path: bash
                  args: [-c, yarn --pure-lockfile]
              output_mapping: {staging: staging-api}

            - task: api-lint
              config:
                platform: linux
                image_resource:
                  <<: *node-image
                inputs: [name: staging-api]
                run:
                  dir: staging-api
                  path: bash
                  args: [-c, yarn lint]

            - task: api-test
              privileged: true
              config:
                platform: linux
                image_resource:
                  type: docker-image
                  source:
                    repository: karlkfi/concourse-dcind
                inputs:
                  - name: staging-api
                  - name: redis
                  - name: postgres
                  - name: node
                run:
                  dir: staging-api
                  path: .concourse/entrypoint.sh
                  args:
                    - bash
                    - -ceux
                    - |
                      docker-compose -f .concourse/integration.yml run app app/.concourse/test-api.sh
                      docker-compose -f .concourse/integration.yml down
                      docker volume rm $(docker volume ls -q)

            - task: api-build
              config:
                platform: linux
                image_resource:
                  <<: *node-image
                inputs: [name: staging-api]
                outputs: [name: staging-api]
                params:
                  FEATURE_PROXY_EDGE_LINKS: "false"
                run:
                  dir: staging-api
                  path: bash
                  args: [-c, yarn build]

            - put: api-deploy
              resource: cf-env
              inputs: [staging-api]
              params:
                command: push
                space: staging
                app_name: federalistapp-staging
                manifest: staging-api/.cloudgov/manifest.yml
                vars_files: [staging-api/.cloudgov/vars/staging.yml]
                strategy: rolling
                path: staging-api

          - do:
            - task: admin-client-install-deps
              config:
                platform: linux
                image_resource:
                  <<: *node-image
                inputs: [name: staging]
                outputs: [name: staging]
                run:
                  dir:  staging/admin-client
                  path: bash
                  args: [-c, yarn --pure-lockfile]
              output_mapping: {staging: staging-admin}

            - task: admin-client-lint
              config:
                platform: linux
                image_resource:
                  <<: *node-image
                inputs: [name: staging-admin]
                run:
                  dir: staging-admin/admin-client
                  path: bash
                  args: [-c, yarn lint]

            - task: admin-client-build
              config:
                platform: linux
                image_resource:
                  <<: *node-image
                inputs: [name: staging-admin]
                outputs: [name: staging-admin]
                params:
                  API_URL: https://federalistapp-staging.18f.gov
                  NODE_ENV: production           
                run:
                  dir: staging-admin/admin-client
                  path: bash
                  args: [-c, yarn build]

            - put: admin-client-deploy
              resource: cf-env
              inputs: [staging-admin]
              params:
                command: push
                space: staging
                app_name: federalist-admin-staging
                manifest: staging-admin/.cloudgov/manifest.yml
                vars_files: [staging-admin/.cloudgov/vars/staging.yml]
                strategy: rolling
                path: staging-admin/admin-client
          
  - name: nightly-tasks
    plan:
      - get: nightly
        trigger: true
      - put: restage
        resource: cf-env
        params:
          command: restage
          space: staging
          app_name: federalistapp-staging    
      - in_parallel:
        - put: archive-build-logs
          resource: cf-env
          params:
            command: run-task
            space: staging
            app_name: federalistapp-staging
            task_command: "yarn archive-build-logs-daily"
            task_name: archive-build-logs
        - put: nightly-builds
          resource: cf-env
          params:
            command: run-task
            space: staging
            app_name: federalistapp-staging
            task_command: "yarn nightly-builds"
            task_name: nightly-builds
        - put: remove-inactive-federalist-users
          resource: cf-env
          params:
            command: run-task
            space: staging
            app_name: federalistapp-staging
            task_command: "yarn remove-inactive-federalist-users"
            task_name: remove-inactive-federalist-users

  - name: every-ten-minutes
    plan:
      - get: every-10m
        trigger: true
      - put: timeout-builds
        resource: cf-env
        params:
          command: run-task
          space: staging
          app_name: federalistapp-staging
          task_command: "yarn timeout-builds"
          task_name: timeout-builds


############################
#  RESOURCES

resources:

  - name: staging
    type: git
    icon: github
    source:
      uri: https://github.com/18F/federalist   
      # branch: staging
      branch: dc/concourse

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/New_York

  - name: every-10m
    type: time
    source: {interval: 10m}

  - name: cf-env
    type: cf-cli-resource
    source:
      api: https://api.fr.cloud.gov
      org: gsa-18f-federalist
      username: ((cf-username))
      password: ((cf-password))
      skip_cert_check: true
      cf_cli_version: 7

  - name: redis
    type: docker-image
    source:
      repository: redis
      tag: 5-alpine

  - name: postgres
    type: docker-image
    source:
      repository: postgres
      tag: 11-alpine

  - name: node
    type: docker-image
    source:
      repository: node
      tag: 14

############################
#  RESOURCE TYPES

resource_types:

  - name: cf-cli-resource
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource
      tag: latest

# fly -t pages-staging sp -p federalistapp-pipeline -c ./.concourse/pipeline.yml -l ./.concourse/vars/.staging.yml