name: federalistapp
memory: 512MB
instances: 2
env: production
env_postfix: ''
log_level: info
feature_auth_github: 'true'
feature_auth_uaa: 'false'
feature_proxy_edge_links: 'false'
feature_proxy_edge_dynamo: 'false'
feature_bull_site_build_queue: 'false'
auth_idp: github
uaa_host: https://uaa.fr.cloud.gov
new_relic_app_name: web
