name: federalistapp-staging
memory: 256MB
instances: 2
env: staging
env_postfix: -staging
log_level: verbose
feature_auth_github: 'false'
feature_auth_uaa: 'true'
feature_proxy_edge_links: 'false'
feature_proxy_edge_dynamo: 'false'
feature_bull_site_build_queue: 'true'
auth_idp: uaa
uaa_host: https://uaa.fr-stage.cloud.gov
new_relic_app_name: web-staging
